package com.fine.fineapp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fine.fineapp.data.bean.ATable;

import com.fine.fineapp.ATableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aTableDaoConfig;

    private final ATableDao aTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aTableDaoConfig = daoConfigMap.get(ATableDao.class).clone();
        aTableDaoConfig.initIdentityScope(type);

        aTableDao = new ATableDao(aTableDaoConfig, this);

        registerDao(ATable.class, aTableDao);
    }
    
    public void clear() {
        aTableDaoConfig.getIdentityScope().clear();
    }

    public ATableDao getATableDao() {
        return aTableDao;
    }

}
