package com.fine.fineapp.data.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ATABLE".
 */
public class ATable {

    private Long guid;
    private String text;
    private Integer status;
    private String bak1;
    private String bak2;
    private java.util.Date createdAt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ATable() {
    }

    public ATable(Long guid) {
        this.guid = guid;
    }

    public ATable(Long guid, String text, Integer status, String bak1, String bak2, java.util.Date createdAt) {
        this.guid = guid;
        this.text = text;
        this.status = status;
        this.bak1 = bak1;
        this.bak2 = bak2;
        this.createdAt = createdAt;
    }

    public Long getGuid() {
        return guid;
    }

    public void setGuid(Long guid) {
        this.guid = guid;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getBak1() {
        return bak1;
    }

    public void setBak1(String bak1) {
        this.bak1 = bak1;
    }

    public String getBak2() {
        return bak2;
    }

    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
